### ISSUE TITLE
Missing `utill/logging`

### ISSUE THREAD

**Issue by stamourv** [LLazarek/utill#2]
The DSSL2 mutation tester you built requires the `utill/logging` module, which does not exist. Did you forget to push updates to this repo?

More generally, I'm wary of depending on misc utility packages, like this one. I tend to prefer relying on only a small number of well-established packages, and only if they're absolutely necessary; small utilities are better off vendored in, IMO.

**Comment by LLazarek** [comment]
@stamourv indeed, feel free to copy the relevant modules from this repo. IIRC that's just `logging.rkt` and `read-module.rkt`
